dependencies:
- appnope=0.1.0=py35_0
- backports.shutil_get_terminal_size=1.0.0=py35_0
- blas=1.1=openblas
- ca-certificates=2016.8.31=0
- certifi=2016.8.31=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- freetype=2.6.3=1
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- libgfortran=3.0.0=0
- libpng=1.6.24=0
- libsodium=1.0.10=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.3=np111py35_0
- mistune=0.7.3=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- ncurses=5.9=9
- notebook=4.2.2=py35_0
- numpy=1.11.1=py35_blas_openblas_201
- openblas=0.2.18=5
- openssl=1.0.2h=2
- pexpect=4.2.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.7=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_1
- pyparsing=2.1.8=py35_0
- pyqt=4.11.4=py35_0
- python=3.5.2=2
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyzmq=15.4.0=py35_0
- qtconsole=4.2.1=py35_0
- readline=6.2=0
- scipy=0.18.0=np111py35_blas_openblas_202
- setuptools=26.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=1
- terminado=0.6=py35_0
- tk=8.5.19=0
- tornado=4.4.1=py35_1
- traitlets=4.3.0=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_3
- xz=5.2.2=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- jupyter=1.0.0=py35_3
- python.app=1.2=py35_4
- qt=4.8.7=4
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - bruges==0.2.1
  - certifi==2016.8.31
  - cycler==0.10.0
  - decorator==4.0.10
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - markupsafe==0.23
  - matplotlib==1.5.3
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - notebook==4.2.2
  - numpy==1.11.1
  - ortools-examples==4.2.3758
  - pexpect==4.2.1
  - pickleshare==0.7.3
  - pip==8.1.2
  - prompt-toolkit==1.0.7
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.8
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - scipy==0.18.0
  - setuptools==26.1.1.post20160901
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - tornado==4.4.1
  - traitlets==4.3.0
  - wcwidth==0.1.7
  - wheel==0.29.0
  - widgetsnbextension==1.2.6

