name: xlines
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - seaborn
  - scipy
  - obspy
  - pandas
  - geopandas
  - scikit-learn
  - basemap
  - folium
  - cartopy
  - jupyter
  - ipykernel
  - pip:
    - bruges
    - welly
