name: xlines
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - seaborn
  - scipy
  - obspy
  - pandas==0.24.2
  - geopandas
  - scikit-learn
  - verde
  - basemap
  - folium
  - cartopy
  - jupyter
  - ipykernel
  - pyfive
  - pint
  - pip
  - pip:
    - plotly-express
    - bruges
    - welly
    - python-ternary
