channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py35_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_0
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2016.8.31=0
- conda-forge::certifi=2016.8.31=py35_0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::entrypoints=0.2.2=py35_0
- conda-forge::freetype=2.6.3=1
- conda-forge::ipykernel=4.5.0=py35_0
- conda-forge::ipython=5.1.0=py35_0
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::ipywidgets=5.2.2=py35_0
- conda-forge::jinja2=2.8=py35_1
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter_client=4.4.0=py35_0
- conda-forge::jupyter_console=5.0.0=py35_0
- conda-forge::jupyter_core=4.2.0=py35_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.24=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::matplotlib=1.5.3=np111py35_0
- conda-forge::mistune=0.7.3=py35_0
- conda-forge::nbconvert=4.2.0=py35_0
- conda-forge::nbformat=4.1.0=py35_0
- conda-forge::ncurses=5.9=9
- conda-forge::notebook=4.2.2=py35_0
- conda-forge::numpy=1.11.1=py35_blas_openblas_201
- conda-forge::openblas=0.2.18=5
- conda-forge::openssl=1.0.2h=2
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pip=8.1.2=py35_0
- conda-forge::prompt_toolkit=1.0.7=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.1.3=py35_1
- conda-forge::pyparsing=2.1.8=py35_0
- conda-forge::pyqt=4.11.4=py35_0
- conda-forge::python=3.5.2=2
- conda-forge::python-dateutil=2.5.3=py35_0
- conda-forge::pytz=2016.6.1=py35_0
- conda-forge::pyzmq=15.4.0=py35_0
- conda-forge::qtconsole=4.2.1=py35_0
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.18.0=np111py35_blas_openblas_202
- conda-forge::setuptools=26.1.1=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_0
- conda-forge::six=1.10.0=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::terminado=0.6=py35_0
- conda-forge::tk=8.5.19=0
- conda-forge::tornado=4.4.1=py35_1
- conda-forge::traitlets=4.3.0=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::widgetsnbextension=1.2.6=py35_3
- conda-forge::xz=5.2.2=0
- conda-forge::zeromq=4.1.5=0
- conda-forge::zlib=1.2.8=3
- jupyter=1.0.0=py35_3
- python.app=1.2=py35_4
- qt=4.8.7=4
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - bruges==0.2.1
  - certifi==2016.8.31
  - cycler==0.10.0
  - decorator==4.0.10
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - markupsafe==0.23
  - matplotlib==1.5.3
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - notebook==4.2.2
  - numpy==1.11.1
  - ortools-examples==4.2.3758
  - pexpect==4.2.1
  - pickleshare==0.7.3
  - pip==8.1.2
  - prompt-toolkit==1.0.7
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.8
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - scipy==0.18.0
  - setuptools==26.1.1.post20160901
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - tornado==4.4.1
  - traitlets==4.3.0
  - wcwidth==0.1.7
  - wheel==0.29.0
  - widgetsnbextension==1.2.6

